log_level: DEBUG
model_dir: models
log_dir: logs
data_dir: data
base_model_id: zamg_vienna_2019_2019_simple_dense
training_data_pickle: zamg_vienna_hourly.pickle
profiling_log_path: logs/profiling_data.csv