services:
  base:
    build: 
      dockerfile: Base.Dockerfile
    ports:
      - "5000:5000"
  sensor1:
    build:
      dockerfile: Sensor.Dockerfile
    command: mock http://base:5000 --mode predict --interval 10 --threshold 2 --id S1
    depends_on:
    - base
